"""Jenkins REST client, and the write-path gate that bounds it.

The gate lives inside `_request`, not inside `post`. A prefix test on `post` alone
is bypassable by any future code path that calls `_request` directly, and a gate
that depends on developers remembering to use the right method is a convention, not
a guarantee.
"""

import base64
import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

from . import PREVIEW_ROOT
from .errors import die
from .names import SAFE_NAME

_WRITE_PREFIX = f"/job/{PREVIEW_ROOT}/"
_TRAVERSAL = ("..", "//", "%2f", "%2F", "%2e", "%2E", "\\")


class _NoRedirect(urllib.request.HTTPRedirectHandler):
    """Refuse to follow redirects.

    urllib's default handler follows 30x and re-issues the request as a GET with no
    body. A proxy that redirects createItem to a login page would then return 200
    from a page that did nothing, and the tool would report success.
    """

    def redirect_request(self, req, fp, code, msg, headers, newurl):  # noqa: ARG002
        return None


def assert_write_path(path: str) -> None:
    """Gate G1. Every write must address a single named item inside the preview root.

    A raw prefix test is not enough: `/job/previews/job/../../x` starts with the
    right prefix and a servlet container may normalise it to `/job/x`. So this
    rejects traversal sequences outright and requires the segment after the preview
    root to be one safe name.
    """
    if not path.startswith(_WRITE_PREFIX):
        die(
            f"refusing to write outside the {PREVIEW_ROOT} folder: {path}",
            f"every write must start with {_WRITE_PREFIX}",
        )
    for bad in _TRAVERSAL:
        if bad in path:
            die(
                f"refusing a write whose path contains {bad!r}: {path}",
                "a traversal sequence could address a job outside the preview folder",
            )

    remainder = path.removeprefix(_WRITE_PREFIX)
    # Either the preview root itself (createItem), or job/<name>/... inside it.
    if remainder.startswith("job/"):
        segment = remainder.removeprefix("job/").split("/", 1)[0]
        if not SAFE_NAME.fullmatch(segment):
            die(
                f"refusing a write to an unsafe folder name {segment!r}",
                "preview folder names may contain only letters, digits, dot, dash and underscore",
            )
    elif remainder == "createItem" or remainder.startswith("createItem?"):
        query = urllib.parse.parse_qs(urllib.parse.urlsplit(path).query)
        name = (query.get("name") or [""])[0]
        if not SAFE_NAME.fullmatch(name):
            die(
                f"refusing createItem without a safe name parameter: {path}",
                "folder creation must name exactly one safe folder",
            )
    else:
        die(
            f"refusing an unrecognised write path: {path}",
            "writes must target createItem in the preview root, or a named folder inside it",
        )


def assert_restore_path(path: str, job: str) -> None:
    """Gate G12. The multijob repair may rewrite exactly one top-level config.xml.

    The multijob plugin's folder-blind delete listener strips phases from
    TOP-LEVEL MultiJobProjects when a same-named preview copy is deleted (see
    multijob.py). Restoring the victim means writing outside /previews, so it
    gets its own narrow gate rather than widening G1: one safe top-level job
    name, the config.xml endpoint, nothing else. Only restore_job_config()
    passes it, and multijob.py only calls that with a config it read from the
    same job moments earlier.
    """
    if not SAFE_NAME.fullmatch(job):
        die(
            f"refusing to restore an unsafe job name {job!r}",
            "restored job names may contain only letters, digits, dot, dash and underscore",
        )
    if path != f"/job/{job}/config.xml":
        die(
            f"refusing an unrecognised restore path: {path}",
            "a repair may only write a top-level job's config.xml",
        )


def assert_view_path(path: str, expected_name: str) -> None:
    """Gate G11. A root view write may address exactly one generated view name.

    Root views live outside the previews folder, so they get their own narrow gate
    rather than widening G1. Only two endpoints are reachable, and only for the name
    this tool generated: no extra query parameters, no caller-supplied suffix.
    """
    if not SAFE_NAME.fullmatch(expected_name):
        die(
            f"refusing to touch an unsafe view name {expected_name!r}",
            "view names are generated by this tool and must be a single safe name",
        )
    quoted = urllib.parse.quote(expected_name, safe="")
    allowed = {f"/createView?name={quoted}", f"/view/{quoted}/doDelete"}
    if path not in allowed:
        die(
            f"refusing an unrecognised view write: {path}",
            "only creating or deleting this tool's own preview view is permitted",
        )


class Jenkins:
    """Minimal Jenkins client. Reads are unrestricted. Writes are gated."""

    def __init__(self, url: str, user: str, token: str) -> None:
        # The gates validate the PATH, and the final URL is base + path. A base URL
        # smuggling a query or fragment would turn the validated path into a query
        # parameter or fragment and redirect the write elsewhere, so the base is
        # validated once, here.
        parsed = urllib.parse.urlsplit(url)
        if parsed.scheme not in {"http", "https"} or not parsed.netloc:
            die(
                f"JENKINS_URL does not look like an http(s) URL: {url!r}",
                "export JENKINS_URL=https://jenkins.example.com",
            )
        if parsed.username or parsed.password:
            die(
                "JENKINS_URL must not carry credentials",
                "use JENKINS_USER and JENKINS_TOKEN instead",
            )
        # "?" and "#" are checked on the raw string: a bare trailing "?" parses to
        # an EMPTY query, which is falsy, and would still shunt every gated path
        # into the query string when concatenated.
        if "?" in url or "#" in url:
            die(
                "JENKINS_URL must not contain '?' or '#'",
                "pass the plain base URL, e.g. https://jenkins.example.com",
            )
        import re as _re

        if parsed.path and not _re.fullmatch(r"(/[A-Za-z0-9._-]+)*/?", parsed.path):
            die(
                f"JENKINS_URL carries an unexpected path {parsed.path!r}",
                "only a plain context path like /jenkins is supported",
            )
        self.url = url.rstrip("/")
        self.user = user
        self._auth = base64.b64encode(f"{user}:{token}".encode()).decode()
        self._opener = urllib.request.build_opener(_NoRedirect)

    def _request(
        self,
        path: str,
        *,
        data: bytes | None = None,
        method: str | None = None,
        content_type: str | None = None,
        view_name: str | None = None,
        restore_job: str | None = None,
    ) -> tuple[int, str]:
        # The gate sits here so nothing can write without passing one of them.
        if (method or "GET").upper() != "GET" or data is not None:
            if view_name is not None:
                assert_view_path(path, view_name)
            elif restore_job is not None:
                assert_restore_path(path, restore_job)
            else:
                assert_write_path(path)

        request = urllib.request.Request(self.url + path, data=data, method=method)
        request.add_header("Authorization", "Basic " + self._auth)
        if content_type:
            request.add_header("Content-Type", content_type)
        try:
            with self._opener.open(request, timeout=60) as response:
                return response.status, response.read().decode("utf-8", "replace")
        except urllib.error.HTTPError as exc:
            # A refused redirect surfaces here. A 302 is legitimate for doDelete.
            return exc.code, exc.read().decode("utf-8", "replace")
        except urllib.error.URLError as exc:
            die(
                f"cannot reach {self.url}: {exc.reason}",
                "check JENKINS_URL, that you are on the right network, and TLS",
            )
        except TimeoutError:
            # A timeout mid-body raises this directly, not URLError. Left uncaught
            # it would escape as a traceback AND, worse, abort a rollback in
            # progress, leaving a half-published folder standing.
            die(
                f"timed out talking to {self.url} on {path}",
                "retry once. If it persists, the master or the network is overloaded",
            )

    def get_json(self, path: str, tree: str | None = None) -> dict[str, Any]:
        """Return parsed api/json, or an empty dict on 404."""
        query = "?tree=" + urllib.parse.quote(tree, safe="[],*") if tree else ""
        status, body = self._request(f"{path}/api/json{query}")
        if status == 404:
            return {}
        self.expect(status, path, (200,))
        return self._parse_json(body, path)

    def exists(self, path: str) -> bool:
        """Explicit existence check. Only 200 means present, only 404 means absent.

        Anything else refuses: treating a 403 or 500 as absence would let a rollback
        report a resource removed while it is still there.
        """
        status, _ = self._request(f"{path}/api/json?tree=name")
        if status == 200:
            return True
        if status == 404:
            return False
        self.expect(status, path, (200, 404))
        raise AssertionError  # unreachable, expect() raised

    def get_text(self, path: str) -> tuple[int, str]:
        return self._request(path)

    def post(
        self, path: str, data: bytes = b"", content_type: str | None = None
    ) -> tuple[int, str]:
        return self._request(path, data=data, method="POST", content_type=content_type)

    def restore_job_config(self, job: str, config_xml: str) -> None:
        """Restore a top-level job's config.xml (gate G12, multijob repair only)."""
        quoted = urllib.parse.quote(job, safe="")
        status, _ = self._request(
            f"/job/{quoted}/config.xml",
            data=config_xml.encode(),
            method="POST",
            content_type="application/xml",
            restore_job=job,
        )
        self.expect(status, f"/job/{job}/config.xml", (200,))

    def create_view(self, name: str, config_xml: str) -> tuple[int, str]:
        """Create a root view. URL built here so no caller can supply a path."""
        quoted = urllib.parse.quote(name, safe="")
        return self._request(
            f"/createView?name={quoted}",
            data=config_xml.encode(),
            method="POST",
            content_type="application/xml",
            view_name=name,
        )

    def delete_view(self, name: str) -> tuple[int, str]:
        """Delete a root view. URL built here so no caller can supply a path."""
        quoted = urllib.parse.quote(name, safe="")
        return self._request(f"/view/{quoted}/doDelete", data=b"", method="POST", view_name=name)

    def view_description(self, name: str) -> str | None:
        """Return a root view's description, or None when the view is absent.

        Only 404 means absent. A 403 or 500 refuses rather than masquerading as
        absence, for the same reason as `exists`.
        """
        quoted = urllib.parse.quote(name, safe="")
        status, body = self._request(f"/view/{quoted}/api/json?tree=description")
        if status == 404:
            return None
        self.expect(status, f"/view/{name}", (200,))
        return self._parse_json(body, f"/view/{name}").get("description") or ""

    @staticmethod
    def _parse_json(body: str, path: str) -> dict[str, Any]:
        """A 200 with a non-JSON body is an interposed page, not an answer."""
        try:
            return json.loads(body)
        except ValueError:
            die(
                f"{path} returned HTTP 200 with a non-JSON body",
                "an authentication proxy probably intercepted the request. Confirm "
                "JENKINS_URL points at Jenkins itself",
            )

    def expect(self, status: int, path: str, ok: tuple[int, ...]) -> None:
        """Turn an HTTP status into an error that names its own fix."""
        if status in ok:
            return
        match status:
            case 401:
                die(
                    "Jenkins rejected the credentials (401)",
                    "regenerate your API token at /me/configure and re-export JENKINS_TOKEN",
                )
            case 403:
                die(
                    f"Jenkins refused the request (403) on {path}",
                    "either your account cannot create or delete jobs here, or you are "
                    "using a password rather than an API token, which fails CSRF crumb "
                    f"checks on POST. Use an API token. If that is already the case, ask "
                    f"a Jenkins admin for permission inside the /{PREVIEW_ROOT} folder",
                )
            case 404:
                die(f"not found on Jenkins: {path}", "check the name with `list`")
            case 301 | 302 | 303 | 307 | 308:
                die(
                    f"Jenkins redirected {path} (HTTP {status}) and the redirect was not followed",
                    "this usually means an authentication proxy intercepted the request. "
                    "confirm JENKINS_URL points at Jenkins itself",
                )
            case _:
                die(
                    f"unexpected HTTP {status} on {path}",
                    "retry once. If it persists this is a Jenkins-side error",
                )
